### ISSUE TITLE
Scouting vision feature extractor

### ISSUE THREAD

**Issue by Francesco-Ranieri** [gianfrancodemarco/mm-cot#10]
Focal points:

- [ ] add features extraction to DVC pipeline
- [ ] add mlflow library to manage the ML lifecycle and track experiments
- [ ] try different pre trained model for vision features extraction:
  - DETR : facebook/deit-base-patch16-224 
  - CLIP: openai/clip-vit-large-patch14-336
  - VITC: google/vit-large-patch16-224-in21k

**Comment by Francesco-Ranieri** [comment]
The code used for this scouting is this one [amazon/mm-cot/issue#35](https://github.com/amazon-science/mm-cot/issues/35).

**Comment by gianfrancodemarco** [comment]
@Francesco-Ranieri we could implement a simple DVC piepeline with a step for the extraction of vision features. We can 2 parameters to chose the model to use for the extraction and the path to the dataframe. What do you think?
